import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className + ' min-h-screen flex flex-col'}>
				<header className="bg-white text-black sticky top-0 z-10">
					<section className="max-w-4xl text-black flex p-4 justify-between items-center mx-auto">
						<h1>CryptoCove</h1>
						<div>
							<button id="mobile-open-button" className="text-3xl sm:hidden focus:outline-none">
								&#9776;
							</button>
							<nav className="hidden sm:block space-x-8 text-xl" aria-label="main">
								<a href="#home" className="hover:opacity-90">
									Home
								</a>
								<a href="#market" className="hover:opacity-90">
									Market
								</a>
								<a href="#choose-us" className="hover:opacity-90">
									Why Us
								</a>
								<a href="#join" className="hover:opacity-90">
									Join
								</a>
							</nav>
						</div>
					</section>
				</header>

				{children}

				<footer className="text-center my-auto p-6">Copyright © 2024 Tyler Mommsen</footer>
			</body>
		</html>
	);
}
